FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

COPY . /usr/src/falcon-7b/

RUN apt-get update -y &&\
    apt-get install -y git-lfs &&\
    apt-get install -y apt-utils &&\
    cd /usr/src/falcon-7b/falcon-7b-instruct && \
    git lfs install &&\
    git lfs pull && \
    apt-get install -y git &&\
    apt-get install -y wget &&\
    cd .. &&\
    pip install -r requirements.txt
    

WORKDIR /usr/src/falcon-7b/

CMD python /usr/src/falcon-7b/app/app_7b.py
